const ITEMS = [
  // =========================================
  // Electronica y gaming (30 items)
  // =========================================
  {
    id: 1,
    nombre: "Consola de Videojuegos Next-Gen 1TB",
    precio: 8999.0,
    categoria: "Electronica y gaming",
    descripcion: "Sumérgete en la nueva generación con 1TB de almacenamiento SSD y soporte para 4K a 120fps.",
    imgurl: "https://loremflickr.com/320/240/console,gaming",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 2,
    nombre: "Laptop Gamer Pro 15.6\" RTX 3060",
    precio: 16499.0,
    categoria: "Electronica y gaming",
    descripcion: "Potencia sin límites con procesador Intel i7, 16GB RAM y gráficos NVIDIA RTX.",
    imgurl: "https://loremflickr.com/320/240/laptop,gaming",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 3,
    nombre: "Audífonos Gamer con Sonido Envolvente",
    precio: 1250.0,
    categoria: "Electronica y gaming",
    descripcion: "Escucha cada detalle con audio 7.1 y micrófono con cancelación de ruido.",
    imgurl: "https://loremflickr.com/320/240/headphones,gaming",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 4,
    nombre: "Smart TV 55\" Crystal 4K UHD",
    precio: 7490.0,
    categoria: "Electronica y gaming",
    descripcion: "Disfruta de colores vibrantes y una nitidez asombrosa en cada escena.",
    imgurl: "https://loremflickr.com/320/240/tv,smart",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 5,
    nombre: "Smartphone Flagship 256GB",
    precio: 12999.0,
    categoria: "Electronica y gaming",
    descripcion: "Cámara de 108MP, pantalla AMOLED 120Hz y carga ultra rápida.",
    imgurl: "https://loremflickr.com/320/240/smartphone",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 6,
    nombre: "Monitor Curvo 27\" 165Hz",
    precio: 4800.0,
    categoria: "Electronica y gaming",
    descripcion: "Experiencia inmersiva para gaming competitivo con 1ms de respuesta.",
    imgurl: "https://loremflickr.com/320/240/monitor,gaming",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 7,
    nombre: "Teclado Mecánico RGB Switch Red",
    precio: 950.0,
    categoria: "Electronica y gaming",
    descripcion: "Interruptores lineales silenciosos y personalización total de luces.",
    imgurl: "https://loremflickr.com/320/240/keyboard,mechanical",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 8,
    nombre: "Mouse Inalámbrico Ultra Ligero",
    precio: 720.0,
    categoria: "Electronica y gaming",
    descripcion: "Sensor de alta precisión y batería de larga duración para jornadas intensas.",
    imgurl: "https://loremflickr.com/320/240/mouse,gaming",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 9,
    nombre: "Tablet para Diseño 11\"",
    precio: 5200.0,
    categoria: "Electronica y gaming",
    descripcion: "Compatible con lápiz óptico, ideal para ilustradores y estudiantes.",
    imgurl: "https://loremflickr.com/320/240/tablet",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 10,
    nombre: "Cámara Digital Vlog 4K",
    precio: 10800.0,
    categoria: "Electronica y gaming",
    descripcion: "Perfecta para creadores de contenido con pantalla abatible y enfoque automático.",
    imgurl: "https://loremflickr.com/320/240/camera,vlog",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 11,
    nombre: "Webcam Full HD 60fps",
    precio: 890.0,
    categoria: "Electronica y gaming",
    descripcion: "Calidad profesional para tus llamadas y streamings con corrección de luz.",
    imgurl: "https://loremflickr.com/320/240/webcam",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 12,
    nombre: "Bocina Inteligente con Asistente",
    precio: 650.0,
    categoria: "Electronica y gaming",
    descripcion: "Controla tu hogar y escucha música con un sonido claro y potente.",
    imgurl: "https://loremflickr.com/320/240/speaker,smart",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 13,
    nombre: "Router WiFi 6 Malla (Pack 2)",
    precio: 3400.0,
    categoria: "Electronica y gaming",
    descripcion: "Elimina las zonas sin señal con cobertura en toda la casa.",
    imgurl: "https://loremflickr.com/320/240/router,wifi",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 14,
    nombre: "Reloj Inteligente Deportivo",
    precio: 2100.0,
    categoria: "Electronica y gaming",
    descripcion: "Monitorea tu salud, sueño y entrenamientos con GPS integrado.",
    imgurl: "https://loremflickr.com/320/240/smartwatch",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 15,
    nombre: "Micrófono de Condensador USB",
    precio: 1400.0,
    categoria: "Electronica y gaming",
    descripcion: "Audio cristalino para podcasts, voces y grabaciones caseras.",
    imgurl: "https://loremflickr.com/320/240/microphone,usb",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 16,
    nombre: "Disco Duro Externo 2TB",
    precio: 1550.0,
    categoria: "Electronica y gaming",
    descripcion: "Almacenamiento portátil seguro para todos tus archivos importantes.",
    imgurl: "https://loremflickr.com/320/240/harddrive,external",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 17,
    nombre: "Silla Gamer Ergonómica Pro",
    precio: 3800.0,
    categoria: "Electronica y gaming",
    descripcion: "Ajuste lumbar y cervical para máxima comodidad durante horas.",
    imgurl: "https://loremflickr.com/320/240/chair,gaming",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 18,
    nombre: "Gafas de Realidad Virtual VR",
    precio: 7990.0,
    categoria: "Electronica y gaming",
    descripcion: "Explora mundos digitales con libertad total y resolución mejorada.",
    imgurl: "https://loremflickr.com/320/240/vr,glasses",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 19,
    nombre: "Tarjeta de Video RTX 3070",
    precio: 11200.0,
    categoria: "Electronica y gaming",
    descripcion: "Gráficos de alta gama para juegos en 1440p y Ray Tracing.",
    imgurl: "https://loremflickr.com/320/240/gpu,rtx",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 20,
    nombre: "Proyector Portátil HD",
    precio: 2900.0,
    categoria: "Electronica y gaming",
    descripcion: "Cine en cualquier lugar, compatible con consolas y apps.",
    imgurl: "https://loremflickr.com/320/240/projector",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 21,
    nombre: "Dron con Cámara 4K",
    precio: 6500.0,
    categoria: "Electronica y gaming",
    descripcion: "Captura tomas aéreas espectaculares con estabilización gimball.",
    imgurl: "https://loremflickr.com/320/240/drone,camera",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 22,
    nombre: "Cargador Inalámbrico Rápido",
    precio: 450.0,
    categoria: "Electronica y gaming",
    descripcion: "Base de carga de 15W compatible con múltiples dispositivos.",
    imgurl: "https://loremflickr.com/320/240/charger,wireless",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 23,
    nombre: "Memoria RAM 16GB (2x8GB) 3200MHz",
    precio: 1200.0,
    categoria: "Electronica and gaming",
    descripcion: "Mejora el rendimiento de tu PC con latencias bajas y RGB.",
    imgurl: "https://loremflickr.com/320/240/ram,pc",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 24,
    nombre: "Fuente de Poder 750W 80+ Gold",
    precio: 1850.0,
    categoria: "Electronica y gaming",
    descripcion: "Energía eficiente y estable para tus componentes de alta gama.",
    imgurl: "https://loremflickr.com/320/240/psu,pc",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 25,
    nombre: "Case Gamer con Cristal Templado",
    precio: 1450.0,
    categoria: "Electronica y gaming",
    descripcion: "Diseño moderno con excelente flujo de aire y espacio para cables.",
    imgurl: "https://loremflickr.com/320/240/pccase,gaming",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 26,
    nombre: "Volante de Carreras Force Feedback",
    precio: 4200.0,
    categoria: "Electronica y gaming",
    descripcion: "Realismo total para simuladores de conducción en PC y Consola.",
    imgurl: "https://loremflickr.com/320/240/steeringwheel,racing",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 27,
    nombre: "Base Enfriadora para Laptop",
    precio: 380.0,
    categoria: "Electronica y gaming",
    descripcion: "Ventiladores silenciosos para mantener tu equipo fresco siempre.",
    imgurl: "https://loremflickr.com/320/240/coolingpad,laptop",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 28,
    nombre: "Control Remoto Universal Smart",
    precio: 290.0,
    categoria: "Electronica y gaming",
    descripcion: "Maneja todos tus dispositivos desde un solo control ergonómico.",
    imgurl: "https://loremflickr.com/320/240/remote,smart",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 29,
    nombre: "Pack de Juegos Clásicos HD",
    precio: 890.0,
    categoria: "Electronica y gaming",
    descripcion: "Colección de títulos icónicos remasterizados para consolas actuales.",
    imgurl: "https://loremflickr.com/320/240/videogames,collection",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 30,
    nombre: "Cable HDMI 2.1 2 Metros",
    precio: 220.0,
    categoria: "Electronica y gaming",
    descripcion: "Alta velocidad certificada para 8K y HDR dinámico.",
    imgurl: "https://loremflickr.com/320/240/hdmi,cable",
    isdashboard: false,
    isFav: false,
  },

  // =========================================
  // Hogar y Electrodomesticos (30 items)
  // =========================================
  {
    id: 31,
    nombre: "Refrigerador Side by Side 25 p3",
    precio: 18990.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Espacio inteligente, despachador de agua y hielo con filtro.",
    imgurl: "https://loremflickr.com/320/240/refrigerator,kitchen",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 32,
    nombre: "Lavadora de Carga Frontal 20 Kg",
    precio: 13500.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Tecnología de ahorro de agua y ciclos de vapor desinfectante.",
    imgurl: "https://loremflickr.com/320/240/washingmachine,home",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 33,
    nombre: "Horno de Microondas Espejo 1.4 p3",
    precio: 2150.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Diseño elegante con funciones de cocción rápida y descongelado.",
    imgurl: "https://loremflickr.com/320/240/microwave,kitchen",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 34,
    nombre: "Licuadora de Alta Potencia 3 Velocidades",
    precio: 890.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Cuchillas de acero inoxidable capaces de triturar hielo en segundos.",
    imgurl: "https://loremflickr.com/320/240/blender,kitchen",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 35,
    nombre: "Sofá Cama Contemporáneo Gris",
    precio: 5800.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Ideal para visitas inesperadas, tela resistente y fácil de limpiar.",
    imgurl: "https://loremflickr.com/320/240/sofa,furniture",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 36,
    nombre: "Freidora de Aire 4.5 Litros Digital",
    precio: 1490.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Cocina saludable sin aceite con panel táctil y recetas integradas.",
    imgurl: "https://loremflickr.com/320/240/airfryer",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 37,
    nombre: "Cafetera de Cápsulas con Espumador",
    precio: 1850.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Prepara lattes y capuchinos como un barista profesional en casa.",
    imgurl: "https://loremflickr.com/320/240/coffeemaker",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 38,
    nombre: "Aspiradora Robot Inteligente",
    precio: 4200.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Limpieza automática programable desde tu smartphone.",
    imgurl: "https://loremflickr.com/320/240/robotvacuum",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 39,
    nombre: "Ventilador de Torre Silencioso",
    precio: 950.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "3 velocidades, oscilación amplia y control remoto incluido.",
    imgurl: "https://loremflickr.com/320/240/fan,tower",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 40,
    nombre: "Plancha de Vapor con Suela Cerámica",
    precio: 580.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Elimina arrugas difíciles rápidamente sin dañar las prendas.",
    imgurl: "https://loremflickr.com/320/240/iron,steam",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 41,
    nombre: "Estufa de 6 Quemadores Acero Inox",
    precio: 7900.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Encendido electrónico y horno con ventana panorámica.",
    imgurl: "https://loremflickr.com/320/240/stove,kitchen",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 42,
    nombre: "Batidora de Inmersión 4 en 1",
    precio: 690.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Incluye picador, batidor de globo y vaso medidor.",
    imgurl: "https://loremflickr.com/320/240/handblender",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 43,
    nombre: "Juego de Sartenes Antiadherentes (3 piezas)",
    precio: 1100.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Aluminio forjado de alta calidad para una cocción uniforme.",
    imgurl: "https://loremflickr.com/320/240/fryingpan",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 44,
    nombre: "Tostador de Pan 2 Rebanadas",
    precio: 420.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Niveles de tostado ajustables y charola para migajas.",
    imgurl: "https://loremflickr.com/320/240/toaster",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 45,
    nombre: "Exprimidor de Cítricos Eléctrico",
    precio: 350.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Jugo natural fresco todas las mañanas sin esfuerzo.",
    imgurl: "https://loremflickr.com/320/240/juicer",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 46,
    nombre: "Mesa de Comedor Redonda 4 Sillas",
    precio: 4900.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Diseño minimalista en madera tratada para espacios pequeños.",
    imgurl: "https://loremflickr.com/320/240/diningtable",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 47,
    nombre: "Escritorio Minimalista para Oficina",
    precio: 1650.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Superficie amplia y compartimento para gestión de cables.",
    imgurl: "https://loremflickr.com/320/240/desk,office",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 48,
    nombre: "Silla de Oficina Ergonómica Malla",
    precio: 1950.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Soporte lumbar ajustable y respaldo transpirable.",
    imgurl: "https://loremflickr.com/320/240/officechair",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 49,
    nombre: "Lámpara de Pie Moderna",
    precio: 720.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Iluminación cálida perfecta para salas o rincones de lectura.",
    imgurl: "https://loremflickr.com/320/240/lamp,floor",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 50,
    nombre: "Set de Cuchillos de Cocina (12 piezas)",
    precio: 890.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Acero inoxidable con base de madera elegante.",
    imgurl: "https://loremflickr.com/320/240/knives,kitchen",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 51,
    nombre: "Colchón Matrimonial Memory Foam",
    precio: 3900.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Descanso reparador que se adapta a la forma de tu cuerpo.",
    imgurl: "https://loremflickr.com/320/240/mattress",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 52,
    nombre: "Organizador de Zapatos 20 Pares",
    precio: 480.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Ahorra espacio y mantén tu calzado ordenado y a la mano.",
    imgurl: "https://loremflickr.com/320/240/shoerack",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 53,
    nombre: "Espejo de Cuerpo Completo con Marco",
    precio: 1100.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Marco de madera color nogal, ideal para recámaras.",
    imgurl: "https://loremflickr.com/320/240/mirror,full",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 54,
    nombre: "Kit de Herramientas Básico (45 piezas)",
    precio: 650.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Todo lo necesario para reparaciones del hogar en un estuche.",
    imgurl: "https://loremflickr.com/320/240/tools,kit",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 55,
    nombre: "Purificador de Agua Sobre Tarja",
    precio: 520.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Agua limpia y segura directamente de tu grifo.",
    imgurl: "https://loremflickr.com/320/240/waterpurifier",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 56,
    nombre: "Báscula Digital de Baño",
    precio: 290.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Cristal templado y medición precisa de alta tecnología.",
    imgurl: "https://loremflickr.com/320/240/scale,bath",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 57,
    nombre: "Set de Toallas de Algodón (4 piezas)",
    precio: 450.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Máxima absorción y suavidad en cada uso.",
    imgurl: "https://loremflickr.com/320/240/towels",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 58,
    nombre: "Cesto para Ropa de Bambú",
    precio: 380.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Elegante y funcional con forro de tela removible.",
    imgurl: "https://loremflickr.com/320/240/laundrybasket",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 59,
    nombre: "Caja Fuerte Digital Compacta",
    precio: 1250.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Protege tus objetos de valor con clave de seguridad.",
    imgurl: "https://loremflickr.com/320/240/safe,box",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 60,
    nombre: "Reloj de Pared Minimalista",
    precio: 210.0,
    categoria: "Hogar y Electrodomesticos",
    descripcion: "Diseño limpio y moderno para cualquier habitación.",
    imgurl: "https://loremflickr.com/320/240/wallclock",
    isdashboard: false,
    isFav: false,
  },

  // =========================================
  // Despensa Basica (30 items)
  // =========================================
  {
    id: 61,
    nombre: "Aceite de Oliva Extra Virgen 1L",
    precio: 145.0,
    categoria: "Despensa Basica",
    descripcion: "Ideal para ensaladas y cocina saludable con sabor premium.",
    imgurl: "https://loremflickr.com/320/240/oliveoil,bottle",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 62,
    nombre: "Arroz Blanco Super Extra 1kg",
    precio: 28.5,
    categoria: "Despensa Basica",
    descripcion: "Granos largos y esponjosos de alta calidad para tus platillos.",
    imgurl: "https://loremflickr.com/320/240/rice,food",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 63,
    nombre: "Frijol Negro Seleccionado 1kg",
    precio: 36.0,
    categoria: "Despensa Basica",
    descripcion: "Frijoles limpios y listos para cocinar, fuente de proteína.",
    imgurl: "https://loremflickr.com/320/240/beans,food",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 64,
    nombre: "Leche Entera 1L (Pack 6)",
    precio: 155.0,
    categoria: "Despensa Basica",
    descripcion: "Leche ultra pasteurizada adicionada con vitaminas A y D.",
    imgurl: "https://loremflickr.com/320/240/milk,carton",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 65,
    nombre: "Café Soluble Clásico 225g",
    precio: 110.0,
    categoria: "Despensa Basica",
    descripcion: "El aroma y sabor de siempre para empezar tus mañanas.",
    imgurl: "https://loremflickr.com/320/240/coffee,jar",
    isdashboard: true,
    isFav: false,
  },
  {
    id: 66,
    nombre: "Azúcar Refinada 1kg",
    precio: 32.0,
    categoria: "Despensa Basica",
    descripcion: "Endulzante natural para tus postres y bebidas favoritas.",
    imgurl: "https://loremflickr.com/320/240/sugar,bag",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 67,
    nombre: "Sal de Mesa Yodada 1kg",
    precio: 14.5,
    categoria: "Despensa Basica",
    descripcion: "Ingrediente esencial para resaltar el sabor de tu comida.",
    imgurl: "https://loremflickr.com/320/240/salt",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 68,
    nombre: "Harina de Trigo 1kg",
    precio: 22.0,
    categoria: "Despensa Basica",
    descripcion: "Ideal para panadería, repostería y capeados.",
    imgurl: "https://loremflickr.com/320/240/flour",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 69,
    nombre: "Pasta para Sopa Espagueti 200g",
    precio: 9.9,
    categoria: "Despensa Basica",
    descripcion: "Sémola de trigo duro de alta calidad.",
    imgurl: "https://loremflickr.com/320/240/pasta,spaghetti",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 70,
    nombre: "Puré de Tomate Condimentado 210g",
    precio: 12.5,
    categoria: "Despensa Basica",
    descripcion: "Base lista para guisos, sopas y salsas caseras.",
    imgurl: "https://loremflickr.com/320/240/tomato,sauce",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 71,
    nombre: "Atún en Agua 140g",
    precio: 19.5,
    categoria: "Despensa Basica",
    descripcion: "Lomo de atún aleta amarilla bajo en sodio.",
    imgurl: "https://loremflickr.com/320/240/tuna,can",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 72,
    nombre: "Mayonesa con Limón 390g",
    precio: 45.0,
    categoria: "Despensa Basica",
    descripcion: "Textura cremosa y sabor equilibrado para tus sándwiches.",
    imgurl: "https://loremflickr.com/320/240/mayonnaise",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 73,
    nombre: "Cereal de Hojuelas de Maíz 700g",
    precio: 68.0,
    categoria: "Despensa Basica",
    descripcion: "Desayuno clásico fortificado con hierro y vitaminas.",
    imgurl: "https://loremflickr.com/320/240/cereal,bowl",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 74,
    nombre: "Mermelada de Fresa 450g",
    precio: 38.0,
    categoria: "Despensa Basica",
    descripcion: "Elaborada con trozos de fruta natural seleccionada.",
    imgurl: "https://loremflickr.com/320/240/jam,strawberry",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 75,
    nombre: "Pan de Caja Integral Grande",
    precio: 52.0,
    categoria: "Despensa Basica",
    descripcion: "Rico en fibra, ideal para una dieta balanceada.",
    imgurl: "https://loremflickr.com/320/240/bread,loaf",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 76,
    nombre: "Galletas Marías 170g",
    precio: 16.0,
    categoria: "Despensa Basica",
    descripcion: "La galleta tradicional para acompañar con café o leche.",
    imgurl: "https://loremflickr.com/320/240/cookies",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 77,
    nombre: "Chocolate en Polvo 400g",
    precio: 49.0,
    categoria: "Despensa Basica",
    descripcion: "Mezcla instantánea para disfrutar caliente o frío.",
    imgurl: "https://loremflickr.com/320/240/chocolate,powder",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 78,
    nombre: "Avena en Hojuelas 1kg",
    precio: 34.0,
    categoria: "Despensa Basica",
    descripcion: "Grano entero natural, fuente de energía duradera.",
    imgurl: "https://loremflickr.com/320/240/oats",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 79,
    nombre: "Jabón de Tocador Frescura (Pack 4)",
    precio: 62.0,
    categoria: "Despensa Basica",
    descripcion: "Limpieza delicada con fragancias naturales.",
    imgurl: "https://loremflickr.com/320/240/soap,bar",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 80,
    nombre: "Papel Higiénico 12 Rollos",
    precio: 85.0,
    categoria: "Despensa Basica",
    descripcion: "Suavidad y resistencia superior en cada hoja.",
    imgurl: "https://loremflickr.com/320/240/toiletpaper",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 81,
    nombre: "Detergente en Polvo 1kg",
    precio: 39.0,
    categoria: "Despensa Basica",
    descripcion: "Remueve manchas difíciles y cuida el color de tus prendas.",
    imgurl: "https://loremflickr.com/320/240/detergent,laundry",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 82,
    nombre: "Suavizante de Telas Aroma Floral 1L",
    precio: 31.0,
    categoria: "Despensa Basica",
    descripcion: "Fragancia duradera y facilidad de planchado.",
    imgurl: "https://loremflickr.com/320/240/fabricsoftener",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 83,
    nombre: "Limpiador Multiusos Pino 1L",
    precio: 26.0,
    categoria: "Despensa Basica",
    descripcion: "Elimina gérmenes y deja un aroma a limpieza profunda.",
    imgurl: "https://loremflickr.com/320/240/cleaner,bottle",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 84,
    nombre: "Bolsas para Basura Grande (10 piezas)",
    precio: 33.0,
    categoria: "Despensa Basica",
    descripcion: "Resistentes y con cinta para fácil amarre.",
    imgurl: "https://loremflickr.com/320/240/garbagebag",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 85,
    nombre: "Crema Dental Protección Total 100ml",
    precio: 24.0,
    categoria: "Despensa Basica",
    descripcion: "Previene caries y mantiene un aliento fresco.",
    imgurl: "https://loremflickr.com/320/240/toothpaste",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 86,
    nombre: "Shampoo Familiar 750ml",
    precio: 58.0,
    categoria: "Despensa Basica",
    descripcion: "Limpieza profunda para todo tipo de cabello.",
    imgurl: "https://loremflickr.com/320/240/shampoo,bottle",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 87,
    nombre: "Desodorante en Spray 150ml",
    precio: 42.0,
    categoria: "Despensa Basica",
    descripcion: "Protección 48 horas contra el mal olor y humedad.",
    imgurl: "https://loremflickr.com/320/240/deodorant,spray",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 88,
    nombre: "Cepillo de Dientes Mediano (Par)",
    precio: 28.0,
    categoria: "Despensa Basica",
    descripcion: "Cerdas cruzadas para una limpieza profunda entre dientes.",
    imgurl: "https://loremflickr.com/320/240/toothbrush",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 89,
    nombre: "Toallitas Húmedas Bebé 80 piezas",
    precio: 45.0,
    categoria: "Despensa Basica",
    descripcion: "Sin alcohol, ideales para pieles sensibles.",
    imgurl: "https://loremflickr.com/320/240/babywipes",
    isdashboard: false,
    isFav: false,
  },
  {
    id: 90,
    nombre: "Lavalozas Líquido Limón 750ml",
    precio: 34.0,
    categoria: "Despensa Basica",
    descripcion: "Arranca la grasa difícil de tus platos rápidamente.",
    imgurl: "https://loremflickr.com/320/240/dishsoap",
    isdashboard: false,
    isFav: false,
  },
];
